all:
  children:
    bastion:
      hosts:
        bastion_host:
          ansible_host: 127.0.0.1 # Dynamic replacement via Jenkins / script
          ansible_user: ubuntu
    monitoring:
      hosts:
        monitoring_server:
          ansible_host: 10.0.10.5 # Dynamic replacement via Jenkins / script
          ansible_user: ubuntu
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@BASTION_IP"'
